In [1]:
#installaling numpy

In [2]:
!pip install numpy

In [4]:
!pip install numpy--upgrade

ERROR: Could not find a version that satisfies the requirement numpy--upgrade (from versions: none)
ERROR: No matching distribution found for numpy--upgrade


In [5]:
import numpy as np

In [6]:
array_1=np.array([1,2,3,4])

In [7]:
array_1

array([1, 2, 3, 4])

In [8]:
print(array_1)

[1 2 3 4]


In [11]:
type(array_1)

numpy.ndarray

In [12]:
digits=[1,2,5,6,7]

In [13]:
array_2=np.array(digits) #passing a list to array

In [14]:
array_2

array([1, 2, 5, 6, 7])

In [15]:
print(array_2)

[1 2 5 6 7]


In [16]:
#printing zero matrix

In [17]:
array_of_zeros=np.zeros((2,3))

In [18]:
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
array_of_ones=np.ones((3,2))

In [20]:
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
#printing array in int data type

In [23]:
array_of_ones_int=np.ones((3,2),dtype=np.int16)

In [24]:
array_of_ones_int

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [25]:
print(array_of_ones_int)

[[1 1]
 [1 1]
 [1 1]]
